FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx-selfsigned.crt /etc/nginx/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/nginx/nginx-selfsigned.key